// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxqnbuwvruutlueadkkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cW5idXd2cnV1dGx1ZWFka2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjkwODEsImV4cCI6MjA2NjgwNTA4MX0.1z7HICG8AigN3f6jNPnFF9grA61CN1pV4CSmuCgh0L0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});